version: '3'
services: 
  local:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5439:5432'
  test-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${TEST_DATABASE_USER}
      POSTGRES_PASSWORD: ${TEST_DATABASE_PASSWORD}
      POSTGRES_DB: $TEST_DATABASE_NAME}
    ports:
      - '5435:5432'

